version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: openbpl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openbpl_user -d openbpl"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openbpl-network

  redis:
    image: redis:8-alpine
    container_name: openbpl-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - openbpl-network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Use development target for local dev
    container_name: openbpl-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      REDIS_URL: "redis://:${REDIS_PASSWORD}@redis:6379"
      PORT: ${PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_EXPIRY: "15m"
    volumes:
      # Mount source code for development (hot reload)
      - .:/app
      - /app/build  # Exclude build directory
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - openbpl-network
    command: ["air", "-c", ".air.toml"]  # Use air for hot reload in development

  # pgAdmin (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: openbpl-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openbpl.local
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - openbpl-network
    profiles:
      - tools  

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: openbpl-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: "redis:redis:6379:0:openbpl_redis_password"
      HTTP_USER: admin
      HTTP_PASSWORD: redis_admin_password
    ports:
      - "8082:8081"
    depends_on:
      - redis
    networks:
      - openbpl-network
    profiles:
      - tools  

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  openbpl-network:
    driver: bridge